"""Media many-to-many taxa

Revision ID: 75b1fa03fbce
Revises: 15e36b617278
Create Date: 2026-07-16 12:40:47.960510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b1fa03fbce'
down_revision = '15e36b617278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxon_media',
    sa.Column('taxon_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxon.id'], ),
    sa.PrimaryKeyConstraint('taxon_id', 'media_id')
    )
    op.execute('INSERT INTO taxon_media (taxon_id, media_id) SELECT taxon_id, id FROM media')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('media_taxon_id_fkey'), type_='foreignkey')
        batch_op.drop_column('taxon_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxon_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('media_taxon_id_fkey'), 'taxon', ['taxon_id'], ['id'])

    op.drop_table('taxon_media')
    # ### end Alembic commands ###
