"""Initial schema

Revision ID: 91717821ec99
Revises: 
Create Date: 2026-07-13 17:37:20.014096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91717821ec99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('geologic_time', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('fossil_site', sa.String(length=250), nullable=True),
    sa.Column('coloration_data', sa.Text(), nullable=True),
    sa.Column('method_used', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxon_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxon_publication',
    sa.Column('taxon_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxon.id'], ),
    sa.PrimaryKeyConstraint('taxon_id', 'publication_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxon_publication')
    op.drop_table('media')
    op.drop_table('taxon')
    op.drop_table('publication')
    # ### end Alembic commands ###
